define ROOT C:\Program Files\nxlog

Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log

<Extension gelf>
    Module xm_gelf
</Extension>

<Input eventlog>
    Module im_msvistalog
</Input>

<Output graylog>
    Module om_tcp
    Host 172.23.50.23
    Port 12201
    OutputType GELF_TCP
</Output>

<Route r>
    Path eventlog => graylog
</Route>